FROM node:20-alpine AS builder

WORKDIR /app

# Copy root workspace configs
COPY package.json tsconfig.base.json ./
COPY packages/shared/package.json ./packages/shared/
COPY packages/config/package.json ./packages/config/
COPY apps/api/package.json ./apps/api/
COPY prisma ./prisma/

RUN npm install

# Copy source files
COPY packages ./packages/
COPY apps/api ./apps/api/

# Generate Prisma Client & Build
RUN npx prisma generate --schema=./prisma/schema.prisma
RUN npm run build --workspace=@fatecode/shared
RUN npm run build --workspace=@fatecode/api

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages/shared/dist ./packages/shared/dist
COPY --from=builder /app/packages/shared/package.json ./packages/shared/package.json
COPY --from=builder /app/apps/api/dist ./apps/api/dist
COPY --from=builder /app/apps/api/package.json ./apps/api/package.json
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

EXPOSE 3001

CMD ["node", "apps/api/dist/src/index.js"]
