import { prisma } from '../plugins/prisma.js';

const samples = [
  {
    title: 'Cardinalidade de conjuntos',
    slug: 'disciplinas-cardinalidade-conjuntos',
    statement: 'Considere A = {1, 2, 3, 4} e B = {3, 4, 5}. Quantos elementos possui A ∪ B?',
    subject: 'DISCRETE_MATHEMATICS',
    exerciseType: 'NUMERIC',
    difficulty: 'BASIC',
    options: null,
    correctAnswer: 5,
    explanation: 'A união contém os elementos distintos {1, 2, 3, 4, 5}, portanto possui 5 elementos.',
    numericTolerance: 0,
    tags: ['conjuntos', 'uniao'],
    xpReward: 25,
  },
  {
    title: 'Implicação lógica',
    slug: 'disciplinas-implicacao-logica',
    statement: 'A proposição p → q é falsa somente quando p é verdadeira e q é falsa.',
    subject: 'DISCRETE_MATHEMATICS',
    exerciseType: 'TRUE_FALSE',
    difficulty: 'BASIC',
    options: null,
    correctAnswer: true,
    explanation: 'Essa é exatamente a única combinação em que uma implicação material é falsa.',
    numericTolerance: null,
    tags: ['logica', 'proposicoes'],
    xpReward: 25,
  },
  {
    title: 'Combinações simples',
    slug: 'disciplinas-combinacoes-simples',
    statement: 'De quantas formas diferentes podemos escolher 2 alunos de um grupo com 5 alunos?',
    subject: 'DISCRETE_MATHEMATICS',
    exerciseType: 'NUMERIC',
    difficulty: 'INTERMEDIATE',
    options: null,
    correctAnswer: 10,
    explanation: 'C(5,2) = 5! / (2!·3!) = 10.',
    numericTolerance: 0,
    tags: ['combinatoria'],
    xpReward: 40,
  },
  {
    title: 'Rastreando uma variável',
    slug: 'disciplinas-rastreando-variavel',
    statement: 'Considere: x ← 2; x ← x + 3; x ← x * 2. Qual é o valor final de x?',
    subject: 'PROGRAMMING_LOGIC',
    exerciseType: 'NUMERIC',
    difficulty: 'BASIC',
    options: null,
    correctAnswer: 10,
    explanation: 'x começa em 2, passa para 5 e depois para 10.',
    numericTolerance: 0,
    tags: ['variaveis', 'algoritmos'],
    xpReward: 25,
  },
  {
    title: 'Estrutura de repetição',
    slug: 'disciplinas-estrutura-repeticao',
    statement: 'Qual estrutura é mais adequada quando sabemos previamente quantas vezes um bloco deve ser repetido?',
    subject: 'PROGRAMMING_LOGIC',
    exerciseType: 'MULTIPLE_CHOICE',
    difficulty: 'BASIC',
    options: ['Seleção simples', 'Laço contado (for)', 'Recursão obrigatória', 'Tratamento de exceção'],
    correctAnswer: 'Laço contado (for)',
    explanation: 'Um laço contado representa diretamente repetições com quantidade conhecida.',
    numericTolerance: null,
    tags: ['repeticao', 'fluxo'],
    xpReward: 25,
  },
  {
    title: 'Curto-circuito booleano',
    slug: 'disciplinas-curto-circuito',
    statement: 'Em uma expressão A E B, se A já é falso, o valor final da conjunção é falso independentemente de B.',
    subject: 'PROGRAMMING_LOGIC',
    exerciseType: 'TRUE_FALSE',
    difficulty: 'INTERMEDIATE',
    options: null,
    correctAnswer: true,
    explanation: 'Na conjunção, basta um operando falso para que o resultado seja falso.',
    numericTolerance: null,
    tags: ['booleanos', 'logica'],
    xpReward: 40,
  },
  {
    title: 'Derivada em um ponto',
    slug: 'disciplinas-derivada-ponto',
    statement: 'Se f(x) = x² + 3x, qual é o valor de f\'(2)?',
    subject: 'CALCULUS',
    exerciseType: 'NUMERIC',
    difficulty: 'BASIC',
    options: null,
    correctAnswer: 7,
    explanation: 'f\'(x) = 2x + 3. Logo, f\'(2) = 4 + 3 = 7.',
    numericTolerance: 0,
    tags: ['derivada'],
    xpReward: 30,
  },
  {
    title: 'Limite fundamental',
    slug: 'disciplinas-limite-fundamental',
    statement: 'Qual é o valor de lim x→0 (sen x / x), considerando x em radianos?',
    subject: 'CALCULUS',
    exerciseType: 'MULTIPLE_CHOICE',
    difficulty: 'INTERMEDIATE',
    options: ['0', '1', '∞', 'Não existe'],
    correctAnswer: '1',
    explanation: 'Esse é um dos limites fundamentais do cálculo diferencial.',
    numericTolerance: null,
    tags: ['limites'],
    xpReward: 40,
  },
  {
    title: 'Integral definida simples',
    slug: 'disciplinas-integral-definida',
    statement: 'Calcule ∫₀² x dx.',
    subject: 'CALCULUS',
    exerciseType: 'NUMERIC',
    difficulty: 'INTERMEDIATE',
    options: null,
    correctAnswer: 2,
    explanation: 'Uma primitiva é x²/2. Avaliando de 0 a 2: 4/2 = 2.',
    numericTolerance: 0.001,
    tags: ['integral'],
    xpReward: 40,
  },
  {
    title: 'Média aritmética',
    slug: 'disciplinas-media-aritmetica',
    statement: 'Qual é a média dos valores 4, 6, 8 e 10?',
    subject: 'STATISTICS',
    exerciseType: 'NUMERIC',
    difficulty: 'BASIC',
    options: null,
    correctAnswer: 7,
    explanation: '(4 + 6 + 8 + 10) / 4 = 7.',
    numericTolerance: 0,
    tags: ['media', 'descritiva'],
    xpReward: 25,
  },
  {
    title: 'Mediana de uma amostra',
    slug: 'disciplinas-mediana-amostra',
    statement: 'Determine a mediana de 2, 3, 5, 8, 12.',
    subject: 'STATISTICS',
    exerciseType: 'NUMERIC',
    difficulty: 'BASIC',
    options: null,
    correctAnswer: 5,
    explanation: 'Com cinco valores ordenados, a mediana é o terceiro valor: 5.',
    numericTolerance: 0,
    tags: ['mediana', 'descritiva'],
    xpReward: 25,
  },
  {
    title: 'Interpretação do desvio padrão',
    slug: 'disciplinas-desvio-padrao',
    statement: 'Mantendo a média constante, um desvio padrão maior indica o quê?',
    subject: 'STATISTICS',
    exerciseType: 'MULTIPLE_CHOICE',
    difficulty: 'INTERMEDIATE',
    options: ['Menor dispersão', 'Maior dispersão', 'Maior média', 'Amostra necessariamente maior'],
    correctAnswer: 'Maior dispersão',
    explanation: 'O desvio padrão mede a dispersão dos valores em torno da média.',
    numericTolerance: null,
    tags: ['desvio-padrao', 'dispersao'],
    xpReward: 40,
  },
  {
    title: 'Função objetivo',
    slug: 'disciplinas-funcao-objetivo',
    statement: 'Em programação linear, a função objetivo representa a grandeza que desejamos maximizar ou minimizar.',
    subject: 'OPERATIONS_RESEARCH',
    exerciseType: 'TRUE_FALSE',
    difficulty: 'BASIC',
    options: null,
    correctAnswer: true,
    explanation: 'Lucro, custo, tempo ou distância são exemplos comuns de grandezas representadas pela função objetivo.',
    numericTolerance: null,
    tags: ['programacao-linear'],
    xpReward: 30,
  },
  {
    title: 'Região viável',
    slug: 'disciplinas-regiao-viavel',
    statement: 'Em um modelo de programação linear, o que define a região viável?',
    subject: 'OPERATIONS_RESEARCH',
    exerciseType: 'MULTIPLE_CHOICE',
    difficulty: 'INTERMEDIATE',
    options: ['Somente a função objetivo', 'O conjunto de restrições', 'A quantidade de variáveis apenas', 'O método Simplex isoladamente'],
    correctAnswer: 'O conjunto de restrições',
    explanation: 'A região viável é formada pelos pontos que satisfazem simultaneamente todas as restrições do modelo.',
    numericTolerance: null,
    tags: ['restricoes', 'programacao-linear'],
    xpReward: 40,
  },
  {
    title: 'Maximização elementar',
    slug: 'disciplinas-maximizacao-elementar',
    statement: 'Maximize Z = 3x + 2y sujeito a x + y ≤ 4, x ≥ 0 e y ≥ 0. Qual é o maior valor possível de Z?',
    subject: 'OPERATIONS_RESEARCH',
    exerciseType: 'NUMERIC',
    difficulty: 'ADVANCED',
    options: null,
    correctAnswer: 12,
    explanation: 'Como x possui maior coeficiente na função objetivo, o ótimo ocorre em x=4, y=0, resultando em Z=12.',
    numericTolerance: 0,
    tags: ['otimizacao', 'programacao-linear'],
    xpReward: 60,
  },
] as const;

export class AcademicCatalogService {
  static async seedValidationCatalog() {
    const result = await (prisma as any).academicExercise.createMany({
      data: samples.map((sample) => ({
        ...sample,
        tags: [...sample.tags],
        isPublished: true,
      })),
      skipDuplicates: true,
    });

    const total = await (prisma as any).academicExercise.count({
      where: { slug: { startsWith: 'disciplinas-' } },
    });

    return { created: result.count, total };
  }
}
